[package]
authors = [ "Khang Le <mkhangle20@gmail.com>" ]
name = "dem"
description = "GoldSrc demo parser and writer library"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/khanghugo/dem"
license-file = "LICENSE"
keywords = [ "goldsrc", "demo" ]
exclude = [ "src/tests" ]

[dependencies]
bitvec = "1.0.1"
hldemo = { git = "https://github.com/YaLTeR/hldemo-rs.git", rev = "cbc1efa212a4fc49c776304058efd07e0369caa7" }
nom = "7.1.3"
